### ISSUE TITLE
How to generate gt pkl?

### ISSUE THREAD

**Issue by lihao0374** [SSLAD2021/AutoScenes-eval#2]
I do not even know the format of gt_pkl ....

**Comment by SSLAD2021** [comment]
Please refer to both [eval.py](https://github.com/SSLAD2021/AutoScenes-eval/blob/main/eval.py) and [bevfusion](https://github.com/mit-han-lab/bevfusion) code. 
We evaluate object detection and segmentation result the same with bevfusion (also as nuScenes devkit).
In order to evaluatethe object detection result and segmentation result together, like the predict file [val demo file](https://drive.google.com/file/d/1KMyMnWwq3UNkQUmKEujk9U4X7joTQHzc/view?usp=sharing), we organize two parts of data in a dict form like 
`{"gt_bev": [bev annotations]; "gt_det": [object detection annotations]}`
For ground truth of bev, it is a `2x200x200` ndarray, each of 200x200 bev mask refer to drivable area/dividers in **lidar coordinate system** which could be generated through bevfusion code.
For ground truth of object detection, gt file contains each gt's translation/size/rotation(in quaterion form) in **global coordinate system** and ego pose calibration to filter gt with max distance. Other keys are not necessary.
